name: norminette

on:
  push:
    branches: [ "*" ]

jobs:
  norm_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure norminette
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install norminette==3.3.51

    - name: norm check
      run: norminette

  test_json:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test json
      run: |
        make json

  test_scene:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test scene
      run: |
        make scene
