name: norminette

on:
  push:
    branches: [ "*" ]

jobs:
  norm_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure norminette
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install norminette==3.3.51

    - name: norm check
      run: norminette

  test_json:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test json
      run: |
        make test_json

  test_scene:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test scene
      run: |
        make test_scene

  test_rt:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test rt
      run: |
        make test_rt

  test_rt_bonus:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test rt bonus
      run: |
        make test_rt_bonus

  test_scene_to_json:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test scene to json
      run: |
        make test_scene_to_json

  test_scene_to_json_bonus:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: test scene to json bonus
      run: |
        make test_scene_to_json_bonus
